# Generated by Django 4.2.7 on 2023-11-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
