# Generated by Django 5.0.1 on 2024-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_profile_alter_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
