# Generated by Django 4.2.10 on 2024-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('EXHIBITOR', 'EXHIBITOR'), ('CUSTOMER', 'CUSTOMER')], default=('EXHIBITOR', 'EXHIBITOR'), max_length=20, verbose_name='نقش'),
        ),
    ]
