# Generated by Django 4.2.10 on 2024-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/<django.db.models.fields.related.OneToOneField>/', verbose_name='تصویر پروفایل'),
        ),
    ]
