# Generated by Django 4.2.10 on 2024-03-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/profiles/default/default.jpeg', upload_to='images/profiles/<django.db.models.fields.related.OneToOneField>/', verbose_name='تصویر پروفایل'),
        ),
    ]
