# Generated by Django 4.2.10 on 2024-03-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('EXHIBITOR', 'EXHIBITOR'), ('CUSTOMER', 'CUSTOMER')], default=('EXHIBITOR', 'EXHIBITOR'), max_length=100, verbose_name='نقش'),
        ),
    ]
