# Generated by Django 4.2.10 on 2024-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('EXHIBITOR', 'EXHIBITOR'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=100, verbose_name='نقش'),
        ),
    ]
