# Generated by Django 4.2.10 on 2025-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_ads',
            field=models.IntegerField(blank=True, default=0, verbose_name='اگهی اضافه'),
        ),
    ]
