# Generated by Django 4.2.10 on 2025-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_user_extra_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_auction',
            field=models.BooleanField(default=False, verbose_name='دیدن مزایده'),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_auction_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای اشتراک دیدن مزایده '),
        ),
    ]
