# Generated by Django 4.2.10 on 2025-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_profile_view_auction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exhibition_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای نمایشگاه'),
        ),
    ]
