# Generated by Django 4.2.10 on 2025-05-29 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0059_remove_transactionlog_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(default=1, verbose_name='تعداد')),
                ('name', models.CharField(max_length=255, verbose_name='اسم')),
                ('type', models.CharField(choices=[('extra_ad', 'اگهی اضافه '), ('is_urgent', 'فوری'), ('is_promoted', 'پیشنهادی'), ('nationwide', 'سراسری'), ('renew', 'تمدید'), ('view_auction', 'دیدن مزایده'), ('submit_exhibition', 'ثبت نمایشگاه')], max_length=255, verbose_name='نوع اشتراک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_default', models.BooleanField(default=False, verbose_name='اشتراک پایه')),
            ],
            options={
                'verbose_name': 'اشتراک ',
                'verbose_name_plural': 'اشتراک ها',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_subscriptions', to='ads.car', verbose_name='اگهی مربوطه')),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscriptions', to='finance.subscriptionplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'ارسال به بانک'), (1, 'پرداخت شده'), (2, 'ناموفق')], default=0, verbose_name='وضعیت پرداخت')),
                ('amount', models.IntegerField(verbose_name='مقدار')),
                ('ref_id', models.CharField(max_length=255, verbose_name='Reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.CharField(max_length=255, unique=True, verbose_name='Authority')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='finance.subscription', verbose_name='اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صورت حساب',
                'verbose_name_plural': 'صورت حساب ها',
            },
        ),
    ]
