# Generated by Django 4.2.10 on 2024-09-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={'verbose_name': 'اعلان پخش همگانی', 'verbose_name_plural': 'اعلان های پخش همگانی'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='message',
            field=models.TextField(verbose_name='محتوای پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='محتوای پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('welcome', 'پیام خوش\u200cآمدگویی'), ('ad_posted', 'تشکر بابت ثبت آگهی'), ('broadcast', 'پیام برادکست'), ('custom', 'سفارشی'), ('status_change', 'تغییر وضعیت')], default='custom', max_length=50, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
