# Generated by Django 4.2.10 on 2024-09-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_broadcastnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_type',
            field=models.CharField(default='custom', max_length=50, verbose_name='نوع پیام'),
        ),
    ]
