# Generated by Django 4.2.10 on 2024-09-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_message_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BroadcastNotification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
