# Generated by Django 4.2.10 on 2024-09-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_delete_broadcastnotification_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='محتوای پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'اعلان پخش همگانی',
                'verbose_name_plural': 'اعلان های پخش همگانی',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('welcome', 'پیام خوش\u200cآمدگویی'), ('ad_posted', 'تشکر بابت ثبت آگهی'), ('broadcast', 'پیام برادکست'), ('custom', 'سفارشی'), ('status_change', 'تغییر وضعیت')], default='custom', max_length=50, verbose_name='نوع پیام')),
                ('message', models.TextField(verbose_name='محتوای پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
