# Generated by Django 5.0.1 on 2024-02-04 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='brand name')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='is negotiable')),
                ('car_type', models.CharField(choices=[('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('کامیون', 'کامیون'), ('اتوبوس', 'اتوبوس'), ('ماشین\u200cآلات سنگین', 'ماشین\u200cآلات سنگین')], max_length=255, verbose_name='car type')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('year', models.PositiveIntegerField(verbose_name='year ')),
                ('kilometer', models.PositiveIntegerField(verbose_name='Mileage kilometers')),
                ('body_type', models.CharField(choices=[('سدان', 'سدان'), ('هاچ\u200cبک', 'هاچ\u200cبک'), ('کراس\u200cاوور', 'کراس\u200cاوور'), ('SUV', 'SUV'), (' وانت', 'وانت'), ('کامیون', 'کامیون')], max_length=255, verbose_name='body type')),
                ('color', models.CharField(max_length=255, verbose_name='رنگ')),
                ('transmission', models.CharField(choices=[('دستی', 'دستی'), ('اتوماتیک', 'اتوماتیک')], max_length=255, verbose_name='transmission type')),
                ('fuel_type', models.CharField(choices=[('بنزین', 'بنزین'), ('گازوئیل', 'گازوئیل'), ('هیبریدی', 'هیبریدی'), ('برقی', 'برقی')], max_length=255, verbose_name='fuel type')),
                ('vin', models.CharField(max_length=255, verbose_name='vin')),
                ('inspection_date', models.DateField(verbose_name='inspection date')),
                ('phone_numbers', models.CharField(max_length=12, verbose_name='phone number')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('pending', 'در حال بررسی'), ('expired', 'منقضی شده')], default='pending', max_length=255, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='is promoted')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.brand', verbose_name='brand')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'ordering': ['-created_at', '-is_promoted'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Car model')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ads.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='features name')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ads.car')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='ads')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_images', to='ads.car')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(to='ads.image', verbose_name='images'),
        ),
    ]
