# Generated by Django 5.0.1 on 2024-02-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_carmodel_options_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
    ]
