# Generated by Django 5.0.1 on 2024-02-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_image_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='seller',
            new_name='user',
        ),
    ]
