# Generated by Django 5.0.1 on 2024-02-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_seller_car_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', 'is_promoted'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
    ]
