# Generated by Django 5.0.1 on 2024-02-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'get_latest_by': 'created_at', 'ordering': ['is_promoted', '-created_at'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
    ]
