# Generated by Django 4.2.10 on 2024-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin',
        ),
        migrations.AddField(
            model_name='car',
            name='body_condition',
            field=models.CharField(blank=True, choices=[('رنگ شدگی', 'رنگ شدگی'), ('بی خط و خش', 'بی خط و خش'), ('دور رنگ', 'دور رنگ'), ('تمام رنگ', 'تمام رنگ')], max_length=255, null=True, verbose_name='car body condition'),
        ),
        migrations.AddField(
            model_name='car',
            name='chassis_condition',
            field=models.CharField(choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم')], default=('سالم', 'سالم'), max_length=255, verbose_name='chassis condition'),
        ),
        migrations.AddField(
            model_name='car',
            name='color_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
