# Generated by Django 4.2.10 on 2024-02-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_remove_car_inspection_date_remove_car_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('بنزین', 'بنزین'), ('گازوئیل', 'گازوئیل'), ('هیبریدی', 'هیبریدی'), ('برقی', 'برقی'), ('دوگانه کارخانه', 'دوگانه کارخانه'), ('دوگانه دستی', 'دوگانه دستی')], max_length=255, verbose_name='fuel type'),
        ),
    ]
