# Generated by Django 4.2.10 on 2024-02-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_car_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
    ]
