# Generated by Django 4.2.10 on 2024-02-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0013_remove_car_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'get_latest_by': 'created_at', 'ordering': ['-is_promoted', '-created_at'], 'verbose_name': 'خودرو', 'verbose_name_plural': 'خودروها'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'مدل', 'verbose_name_plural': 'مدل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'امکانات', 'verbose_name_plural': 'امکانات'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_condition',
            field=models.CharField(blank=True, choices=[('رنگ شدگی', 'رنگ شدگی'), ('بی خط و خش', 'بی خط و خش'), ('دور رنگ', 'دور رنگ'), ('تمام رنگ', 'تمام رنگ')], max_length=255, null=True, verbose_name='وضعیت بدنه خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('سدان', 'سدان'), ('هاچ\u200cبک', 'هاچ\u200cبک'), ('کراس\u200cاوور', 'کراس\u200cاوور'), ('SUV', 'SUV'), (' وانت', 'وانت'), ('کامیون', 'کامیون')], max_length=255, verbose_name='نوع بدنه'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('کامیون', 'کامیون'), ('اتوبوس', 'اتوبوس'), ('ماشین\u200cآلات سنگین', 'ماشین\u200cآلات سنگین')], max_length=255, verbose_name='نوع خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis_condition',
            field=models.CharField(choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم')], default=('سالم', 'سالم'), max_length=255, verbose_name='وضعیت شاسی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color_description',
            field=models.TextField(blank=True, null=True, verbose_name='جزعیات رنگ شدگی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('بنزین', 'بنزین'), ('گازوئیل', 'گازوئیل'), ('هیبریدی', 'هیبریدی'), ('برقی', 'برقی'), ('دوگانه کارخانه', 'دوگانه کارخانه'), ('دوگانه دستی', 'دوگانه دستی')], max_length=255, verbose_name='نوع سوخت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_negotiable',
            field=models.BooleanField(default=True, verbose_name='قابل مذاکره'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kilometer',
            field=models.PositiveIntegerField(verbose_name='کارکرد کیلومتر'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.carmodel', verbose_name='مدل خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone_numbers',
            field=models.CharField(max_length=12, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('pending', 'در حال بررسی'), ('expired', 'منقضی شده')], default='pending', max_length=255, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('دستی', 'دستی'), ('اتوماتیک', 'اتوماتیک')], max_length=255, verbose_name='نوع گیربکس'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ads.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='مدل خودرو'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ads.car', verbose_name='خودرو'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255, verbose_name='امکانات'),
        ),
        migrations.AlterField(
            model_name='image',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.car', verbose_name='آگهی'),
        ),
    ]
