# Generated by Django 4.2.10 on 2024-02-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0015_car_view_count_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='نام شرکت')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='نام تماس')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن تماس')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('social_media_links', models.JSONField(blank=True, default=dict, verbose_name='لینک\u200cهای شبکه\u200cهای اجتماعی')),
                ('logo', models.ImageField(blank=True, upload_to='exhibition_logos', verbose_name='لوگو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('video_file', models.FileField(upload_to='exhibition_videos', verbose_name='فایل ویدیو')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.exhibition', verbose_name='غرفه دار')),
            ],
        ),
    ]
