# Generated by Django 4.2.10 on 2024-02-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_exhibition_exhibitionvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام نماینده '),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='social_media_links',
            field=models.TextField(blank=True, default=dict, verbose_name='لینک\u200cهای شبکه\u200cهای اجتماعی'),
        ),
    ]
