# Generated by Django 4.2.10 on 2024-02-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_alter_exhibition_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionvideo',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ads.exhibition', verbose_name='غرفه دار'),
        ),
    ]
