# Generated by Django 4.2.10 on 2024-03-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_alter_exhibitionvideo_exhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exhibition_videos', verbose_name='فایل ویدیو'),
        ),
    ]
