# Generated by Django 4.2.10 on 2024-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_exhibitionvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='exhibition_logos', verbose_name='لوگو'),
        ),
    ]
