# Generated by Django 4.2.10 on 2024-03-03 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0020_alter_exhibition_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.exhibition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exh')},
            },
        ),
    ]
