# Generated by Django 4.2.10 on 2024-03-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_exhview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
