# Generated by Django 4.2.10 on 2024-03-03 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0022_remove_exhibition_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhview',
            name='exh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.exhibition'),
        ),
        migrations.AlterField(
            model_name='exhview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
