# Generated by Django 4.2.10 on 2024-03-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_alter_exhview_exh_alter_exhview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='تلفن تماس'),
        ),
    ]
