# Generated by Django 4.2.10 on 2024-03-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_alter_exhibition_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='ads.exhibition', verbose_name='نمایشگاه'),
        ),
    ]
