# Generated by Django 4.2.10 on 2024-03-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_alter_car_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='promoted_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدل پیشنهادی '),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.carmodel', verbose_name='مدل خودرو'),
        ),
    ]
