# Generated by Django 4.2.10 on 2024-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_alter_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='payload_capacity',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='حداکثر وزن ناخالص مجاز وسیله نقلیه'),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='وزن ماشین'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheel_number',
            field=models.SmallIntegerField(default=4, verbose_name='تعداد چرخ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('سدان', 'سدان'), ('هاچ\u200cبک', 'هاچ\u200cبک'), ('کراس\u200cاوور', 'کراس\u200cاوور'), ('SUV', 'SUV'), (' وانت', 'وانت'), ('کامیون', 'کامیون')], max_length=255, null=True, verbose_name='نوع بدنه'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('اتوبوس', 'اتوبوس'), ('ماشین\u200cآلات سنگین', 'ماشین\u200cآلات سنگین')], max_length=255, verbose_name='نوع خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis_condition',
            field=models.CharField(blank=True, choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم')], default=('سالم', 'سالم'), max_length=255, null=True, verbose_name='وضعیت شاسی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('دستی', 'دستی'), ('اتوماتیک', 'اتوماتیک')], max_length=255, null=True, verbose_name='نوع گیربکس'),
        ),
    ]
