# Generated by Django 4.2.10 on 2024-03-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_car_payload_capacity_car_weight_car_wheel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='payload_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر وزن ناخالص مجاز وسیله نقلیه'),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن ماشین'),
        ),
    ]
