# Generated by Django 4.2.10 on 2024-04-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0034_car_ads_car_brand_i_a09a10_idx_exhibition_city_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='car',
            name='ads_car_brand_i_a09a10_idx',
        ),
        migrations.RemoveIndex(
            model_name='exhibition',
            name='city_index',
        ),
        migrations.RemoveIndex(
            model_name='exhibition',
            name='Company_name_index',
        ),
    ]
