# Generated by Django 4.2.10 on 2024-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_remove_car_ads_car_brand_i_a09a10_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model'], name='ads_car_brand_i_a09a10_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibition',
            index=models.Index(fields=['city'], name='city_index'),
        ),
        migrations.AddIndex(
            model_name='exhibition',
            index=models.Index(fields=['company_name'], name='Company_name_index'),
        ),
    ]
