# Generated by Django 4.2.10 on 2024-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0036_car_ads_car_brand_i_a09a10_idx_exhibition_city_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
