# Generated by Django 4.2.10 on 2024-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0036_car_ads_car_brand_i_a09a10_idx_exhibition_city_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='sells_chinese_cars',
            field=models.BooleanField(default=False, verbose_name='فروش ماشین\u200cهای چینی'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='sells_domestic_cars',
            field=models.BooleanField(default=False, verbose_name='فروش ماشین\u200cهای داخلی'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='sells_foreign_cars',
            field=models.BooleanField(default=False, verbose_name='فروش ماشین\u200cهای خارجی'),
        ),
    ]
