# Generated by Django 4.2.10 on 2024-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0037_exhibition_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="sale_or_rent",
            field=models.CharField(
                choices=[("sale", "فروشی"), ("rent", "اجاره\u200cای")],
                default="sale",
                max_length=255,
                verbose_name="فروشی یا اجاره\u200cای",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="tire_condition",
            field=models.CharField(
                blank=True,
                choices=[("new", "نو"), ("good", "خوب"), ("worn", "فرسوده")],
                max_length=255,
                null=True,
                verbose_name="وضعیت لاستیک",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="upholstery_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leather", "روکش چرم"),
                    ("none", "بدون روکش"),
                    ("fabric", "روکش پارچه ای"),
                ],
                max_length=255,
                null=True,
                verbose_name="وضعیت مبلمان",
            ),
        ),
    ]
