# Generated by Django 4.2.10 on 2024-05-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0037_exhibition_sells_chinese_cars_and_more'),
        ('ads', '0038_car_sale_or_rent_car_tire_condition_and_more'),
    ]

    operations = [
    ]
