# Generated by Django 4.2.10 on 2024-06-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0039_merge_20240526_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_condition',
            field=models.CharField(choices=[('رنگ شدگی', 'رنگ شدگی'), ('بی خط و خش', 'بی خط و خش'), ('دور رنگ', 'دور رنگ'), ('تمام رنگ', 'تمام رنگ')], max_length=255, null=True, verbose_name='وضعیت بدنه خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis_condition',
            field=models.CharField(choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم')], default=('سالم', 'سالم'), max_length=255, null=True, verbose_name='وضعیت شاسی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ads.carmodel', verbose_name='مدل خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tire_condition',
            field=models.CharField(choices=[('new', 'نو'), ('good', 'خوب'), ('worn', 'فرسوده')], max_length=255, null=True, verbose_name='وضعیت لاستیک'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('دستی', 'دستی'), ('اتوماتیک', 'اتوماتیک')], max_length=255, null=True, verbose_name='نوع گیربکس'),
        ),
        migrations.AlterField(
            model_name='car',
            name='upholstery_condition',
            field=models.CharField(choices=[('leather', 'روکش چرم'), ('none', 'بدون روکش'), ('fabric', 'روکش پارچه ای')], max_length=255, null=True, verbose_name='وضعیت مبلمان'),
        ),
    ]
