# Generated by Django 4.2.10 on 2024-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0040_alter_car_body_condition_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_condition',
            field=models.CharField(blank=True, choices=[('رنگ شدگی', 'رنگ شدگی'), ('بی خط و خش', 'بی خط و خش'), ('دور رنگ', 'دور رنگ'), ('تمام رنگ', 'تمام رنگ')], max_length=255, null=True, verbose_name='وضعیت بدنه خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis_condition',
            field=models.CharField(blank=True, choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم')], default=('سالم', 'سالم'), max_length=255, null=True, verbose_name='وضعیت شاسی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tire_condition',
            field=models.CharField(blank=True, choices=[('new', 'نو'), ('good', 'خوب'), ('worn', 'فرسوده')], max_length=255, null=True, verbose_name='وضعیت لاستیک'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('دستی', 'دستی'), ('اتوماتیک', 'اتوماتیک')], max_length=255, null=True, verbose_name='نوع گیربکس'),
        ),
        migrations.AlterField(
            model_name='car',
            name='upholstery_condition',
            field=models.CharField(blank=True, choices=[('leather', 'روکش چرم'), ('none', 'بدون روکش'), ('fabric', 'روکش پارچه ای')], max_length=255, null=True, verbose_name='وضعیت مبلمان'),
        ),
    ]
