# Generated by Django 4.2.10 on 2024-07-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0041_alter_car_body_condition_alter_car_chassis_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('سدان', 'سدان'), ('هاچ\u200cبک', 'هاچ\u200cبک'), ('کراس\u200cاوور', 'کراس\u200cاوور'), ('SUV', 'SUV'), (' وانت', 'وانت'), ('کامیون', 'کامیون'), ('تجهیزات', 'تجهیزات')], max_length=255, null=True, verbose_name='نوع بدنه'),
        ),
        migrations.CreateModel(
            name='SelectedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(choices=[('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('ماشین\u200cآلات سنگین', 'ماشین\u200cآلات سنگین')], max_length=40, verbose_name='دسته بندی برند')),
                ('brand', models.ManyToManyField(related_name='selected_brand', to='ads.brand', verbose_name='برند های منتخب')),
            ],
            options={
                'verbose_name': 'برند منتخب',
                'verbose_name_plural': 'برند های منتخب',
            },
        ),
    ]
