# Generated by Django 4.2.10 on 2024-09-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0044_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='رنگ')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='suggested_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رنگ پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.color', verbose_name='رنگ'),
        ),
    ]
