# Generated by Django 4.2.10 on 2024-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0045_color_car_suggested_color_alter_car_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='suggested_color',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رنگ'),
        ),
    ]
