# Generated by Django 4.2.10 on 2024-09-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0046_remove_car_suggested_color_alter_car_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
