# Generated by Django 4.2.10 on 2024-09-20 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0048_color_car_suggested_color_alter_car_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='chassis_condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='color_description',
        ),
        migrations.AddField(
            model_name='brand',
            name='type',
            field=models.CharField(choices=[('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('ماشین\u200cآلات سنگین', 'ماشین\u200cآلات سنگین')], default=(('سواری', 'سواری'),), max_length=255, verbose_name='نوع خودرو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='behind_chassis_condition',
            field=models.CharField(blank=True, choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم'), ('رنگ شده', 'رنگ شده')], default=('سالم', 'سالم'), max_length=255, null=True, verbose_name='وضعیت شاسی'),
        ),
        migrations.AddField(
            model_name='car',
            name='front_chassis_condition',
            field=models.CharField(blank=True, choices=[('ضربه خورده', 'ضربه خورده'), ('سالم', 'سالم'), ('رنگ شده', 'رنگ شده')], default=('سالم', 'سالم'), max_length=255, null=True, verbose_name='وضعیت شاسی'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='بیمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(choices=[('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('اتوبوس', 'اتوبوس'), ('ماشین\u200cآلات سنگین', 'ماشین\u200cآلات سنگین')], default=(('سواری', 'سواری'),), max_length=255, verbose_name='نوع خودرو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='body_condition',
            field=models.CharField(blank=True, choices=[('بدون رنگ', 'بدون رنگ'), ('صافکاری بدون رنگ', 'صافکاری بدون رنگ'), ('یه لکه رنگ', 'یه لکه رنگ'), ('دو لکه رنگ', 'دو لکه رنگ'), ('سه لکه رنگ', 'سه لکه رنگ'), ('چند لکه رنگ', 'چند لکه رنگ'), ('کامل رنگ', 'کامل رنگ'), ('دور رنگ', 'دور رنگ'), ('تصادفی', 'تصادفی'), ('اتاق تعویض', 'اتاق تعویض'), ('سوخته', 'سوخته'), ('اوراقی', 'اوراقی')], max_length=255, null=True, verbose_name='وضعیت بدنه خودرو'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
