# Generated by Django 4.2.10 on 2024-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0050_car_is_urgent_alter_car_behind_chassis_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
    ]
