# Generated by Django 4.2.10 on 2025-04-17 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0051_alter_car_address_alter_exhibition_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(default=1, verbose_name='تعداد')),
                ('name', models.CharField(max_length=255, verbose_name='اسم')),
                ('type', models.CharField(choices=[('extra_ad', 'اگهی اضافه '), ('is_urgent', 'فوری'), ('is_promoted', 'پیشنهادی'), ('nationwide', 'سراسری')], max_length=255, verbose_name='نوع اشتراک')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_subscription_plans', to='ads.car', verbose_name='اگهی مربوطه')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('ref_id', models.CharField(max_length=255, verbose_name='Reference ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.subscriptionplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
    ]
