# Generated by Django 4.2.10 on 2025-04-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0052_subscriptionplans_transactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplans',
            name='ad',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_subscription_plans', to='ads.car', verbose_name='اگهی مربوطه'),
        ),
    ]
