# Generated by Django 4.2.10 on 2025-04-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0053_remove_subscriptionplans_ad_transactionlog_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplans',
            options={'verbose_name': 'اشتراک ', 'verbose_name_plural': 'اشتراک ها'},
        ),
    ]
