# Generated by Django 4.2.10 on 2025-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0054_alter_subscriptionplans_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
