# Generated by Django 4.2.10 on 2025-04-28 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0055_subscriptionplans_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='user',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_subscriptions', to='ads.car', verbose_name='اگهی مربوطه')),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_subscriptions', to='ads.subscriptionplans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_transactions', to='ads.subscription'),
        ),
    ]
