# Generated by Django 4.2.10 on 2025-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0056_remove_transactionlog_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='اشتراک پایه'),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='type',
            field=models.CharField(choices=[('extra_ad', 'اگهی اضافه '), ('is_urgent', 'فوری'), ('is_promoted', 'پیشنهادی'), ('nationwide', 'سراسری'), ('renew', 'تمدید'), ('view_auction', 'دیدن مزایده')], max_length=255, verbose_name='نوع اشتراک'),
        ),
    ]
