# Generated by Django 4.2.10 on 2025-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0057_subscriptionplans_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplans',
            name='type',
            field=models.CharField(choices=[('extra_ad', 'اگهی اضافه '), ('is_urgent', 'فوری'), ('is_promoted', 'پیشنهادی'), ('nationwide', 'سراسری'), ('renew', 'تمدید'), ('view_auction', 'دیدن مزایده'), ('submit_exhibition', 'ثبت نمایشگاه')], max_length=255, verbose_name='نوع اشتراک'),
        ),
    ]
