# Generated by Django 4.2.10 on 2025-05-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0058_alter_subscriptionplans_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlans',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
