# Generated by Django 5.0.1 on 2024-02-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='memeber',
        ),
    ]
