# Generated by Django 4.2.10 on 2024-02-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_image_title'),
        ('chat', '0006_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ads.car', verbose_name=' اگهی مربوط'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='roomName',
            field=models.CharField(max_length=50, verbose_name='نام چت'),
        ),
    ]
