# Generated by Django 4.2.10 on 2024-02-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_ad_alter_chat_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='ad',
        ),
    ]
