# Generated by Django 4.2.10 on 2024-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chat_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='max_users',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='chat',
            name='roomName',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام چت'),
        ),
    ]
