# Generated by Django 4.2.10 on 2024-02-14 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_chat_max_users_alter_chat_roomname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='roomName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام چت'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
