# Generated by Django 4.2.10 on 2024-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_roomname_alter_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='roomName',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام چت'),
        ),
    ]
