# Generated by Django 4.2.10 on 2024-02-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0012_alter_chat_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'چت', 'verbose_name_plural': 'چت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='chat_image',
            options={'verbose_name': 'تصویر چت', 'verbose_name_plural': 'تصاویر چت'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='max_users',
            field=models.PositiveIntegerField(default=2, verbose_name='حداکثر کاربران'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='roomName',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام اتاق چت'),
        ),
        migrations.AlterField(
            model_name='chat_image',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.chat', verbose_name='چت'),
        ),
        migrations.AlterField(
            model_name='chat_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='چت'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='محتوای پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
    ]
