# Generated by Django 4.2.10 on 2024-02-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chat_options_alter_chat_image_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='max_users',
        ),
    ]
