# Generated by Django 4.2.10 on 2024-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='auction_images', verbose_name='تصویر')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت پایه')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('ENDED', 'پایان یافته')], default='ACTIVE', max_length=255, verbose_name='وضعیت')),
            ],
        ),
    ]
