# Generated by Django 4.2.10 on 2024-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_auction_end_date_alter_auction_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name': 'مزایده', 'verbose_name_plural': 'مزایده ها'},
        ),
    ]
