# Generated by Django 4.2.10 on 2024-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0005_alter_auction_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="auction_type",
            field=models.CharField(
                choices=[("MISC", "متفرقه"), ("PROPERTY", "ملک"), ("CAR", "ماشین")],
                default="CAR",
                max_length=255,
                verbose_name="نوع مزایده",
            ),
        ),
    ]
