# Generated by Django 4.2.10 on 2024-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0006_auction_auction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="auction_images", verbose_name="تصویر"
            ),
        ),
    ]
