# Generated by Django 4.2.10 on 2024-10-17 14:56

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_auction_auction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
