# Generated by Django 4.2.10 on 2025-04-17 07:25

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_add_auction_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
