# Generated by Django 4.2.10 on 2025-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auction_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد اگهی'),
        ),
        migrations.AddField(
            model_name='auction',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='برگذار کننده'),
        ),
    ]
